name: Build wp_publisher
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pip install -r requirements.txt
      - run: pyinstaller --onefile wp_publish_news.py
      - uses: actions/upload-artifact@v4
        with:
          name: wp_publish_news
          path: dist/wp_publish_news.exe
